apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: quarkusgitlab
  janus-idp.io/tekton: quarkusgitlab
  backstage.io/kubernetes-id: quarkusgitlab
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: quarkusgitlab
resources:
- deployment.yaml
- route.yaml
- service.yaml
